package com.backtracking;

/**
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added
 * @author nisheedh
 *
 */
public class StringDifference {

    public char findTheDifference(String s, String t) {
        int ts = getSum(t);
        int ss = getSum(s);
        return (char) (ts- ss);
    }

	private int getSum(String t) {
		int sum	= 0;
		for (int i = 0; i < t.length() ; ++i) {
			sum += t.charAt(i);
		}
		return sum;
	}
}
